yocto-layer-check: fixed Upstream Status of ishape patch
AssertionError: 1 != 0 : Found following patches with malformed or missing upstream status:
.../meta-opendds/recipes-connectivity/opendds/opendds/0001-adding-the-ishapes-demo.patch

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>